# Generated by Django 4.2.1 on 2023-05-29 08:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("kind", models.CharField(max_length=20)),
                (
                    "current_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateTimeField()),
                ("creator", models.CharField(max_length=200)),
                ("assignee", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("O", "Open"), ("C", "Closed")],
                        default="O",
                        max_length=1,
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[("3", "大"), ("2", "中"), ("1", "小")],
                        default="2",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_number", models.IntegerField()),
                ("content", models.TextField()),
                ("user_id", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="myapp.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("task_id", "comment_number")},
            },
        ),
    ]
