# Generated by Django 4.2.1 on 2023-05-29 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("task_id", "comment_id")},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment_number",
        ),
    ]
