# Generated by Django 4.2.1 on 2023-05-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_comment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together={("task_id", "comment_number")},
        ),
    ]
