# Generated by Django 4.2.1 on 2023-05-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_comment_unique_together_comment_comment_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_number",
            field=models.IntegerField(default=0),
        ),
    ]
