# Generated by Django 4.2.1 on 2023-06-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="current_time",
            field=models.DateTimeField(),
        ),
    ]
